### ISSUE TITLE
$assert cells should be ignored during synthesis

### ISSUE THREAD

**Issue by whitequark** [azonenberg/openfpga#11]
Currently the SystemVerilog `assert property (...);` causes this PAR error:

```
ERROR: Cell "$techmap\core.$assert$foo.v:61$28" is of type "$assert" which is not a valid GreenPak4 primitive
```

I think they should be removed. But I'm not sure at what stage, since, assuming it reaches PAR, it probably drags some synthesized logic with it, so maybe yosys should do that?

**Comment by azonenberg** [comment]
Best option is probably to add a flag (enabled by default) to synth_greenpak4 that strips out $assert cells then re-runs optimization to remove any logic driving the assert cell. This could be set to false for formal testbenches.

Closing since this is a Yosys issue, not a PAR problem. Re-file a ticket against Yosys if you want to pursue this further.
