### ISSUE TITLE
cheat code support for the pocket cores

### ISSUE THREAD

**Issue by ThetaX55** [azonenberg/openfpga#141]
Cheats in pocket cores.
In the menu or something.
More savestat support for the cores.

**Comment by ThetaX55** [comment]
also join to ip for second player.

**Comment by ArcaneNibble** [comment]
Hi, you are extremely lost and in the wrong place.

Using my psychic debugging abilities, I believe you may be looking for https://github.com/agg23?tab=repositories

**Comment by cyrozap** [comment]
Assuming they're not a bot, judging by [their repos](https://github.com/ThetaX55?tab=repositories) and their requests (it sounds like they're talking about FPGA-based video game console emulation) I think they're looking for https://github.com/open-fpga.

@ThetaX55, this is a repository for an open source FPGA _toolchain_, not for FPGA-based emulator cores. In fact this repository has absolutely nothing to do with video game emulation, and continuing to comment on this issue is not going to solve whatever issues you're having.
